INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('800218654','AGROMUNDO','cra 31 51-74 ofi 901 (bucaramanga)','6436070','patriciagarcia@agromundoltda.com','agromundo',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('804004906','AGROSOL','cra 31 # 51-74 ofc. 101 torre mardel (bucaramanga)','6436070','','agrosol',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('1388199','ALFONSO CASTELLANOS','cra 29 36 - 12','','','alfonso_castellanos',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('9001331144','ALIADOS ESTRATEGICOS LTDA','CLL 51 #35-28 INT 100 OFIC 218','','','aliados_estrategicos_ltda',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('804016472','AMERICANA DE SERVICIOS LTDA','calle 104 # 19-21 provenza (bucaramanga)','6367434','mejoraseo@hotmail.com','americana_de_servicios_ltda',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('804001168','APOYO TEMPORAL RECURSO HUMANO','CRA 34 #52-78 CAMARA COMERCIO','','','apoyo_temporal_recurso_humano',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('860006127','CI SOCIEDAD INDUSTRIAL DE GRASAS VEGETALES SIGRA SA','cra. 46 # 13 - 95 bogota d.c. (bogota)','5190900','','ci_sociedad_industrial_de_grasas_vegetales_sigra_sa',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('79556476','CLINICA ODONTOLOGICA CESAAR FIGUEROA','calle 52 n. 31-32 (bucaramanga)','6470058','leidy-0605@hotmail.com','clinica_odontologica_cesaar_figueroa',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('890300225','COEXITO','cra 15 # 28-36 (bucaramanga)','6336836','analistaso@coexito.com.co','coexito',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('890908493','COMESTIBLES DANN','cra 41 # 46-81 (bucaramanga)','6374000','','comestibles_dann',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('9005917648','CONSTRUMER MBG','cll 34 # 24-60 (bucaramanga)','6357844','construmer_11@hotmail.com','construmer_mbg',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('890203088','COOPCENTRAL','cra 19 # 34-14 (bucaramanga)','6330822','gestion.humana@coopcentral.com.co','coopcentral',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('900187021','COOPERSALUD','cll 52B #31-102','','','coopersalud',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('830071113','COSMETIC FASHION CORPORATION SA','','','','cosmetic_fashion_corporation_sa',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('900582900','CSI CONSTRUCCIONES SERVICIOS INDUSTRILIZADOS SAS','cll 21 # 8-06 (cucuta)','','','csi_construcciones_servicios_industrilizados_sas',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('900631958','CYAFIN SAS','','','','cyafin_sas',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('800166199','DELTEC','cll 102 # 21-152 provenza (bucaramanga)','6363677','','deltec',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('37520586','DIANA YORLEY VESGA PEREZ','barrancabermeja el llanito','','','diana_yorley_vesga_perez',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('890206735','DISTRIBUCIONES COLOMBIA','diag 15 # 59-14 (bucaramanga)','6573000','recursohumano@distribucionescolombia.com','distribuciones_colombia',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('830147160','DRYWALL ARQUITECTURA','cll 61 #17a-29','3123791041','','drywall_arquitectura',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('900668458','ELB GEOLOGIA Y VIAS SAS','cra 23 # 37 - 47 apt 15-04 (bucaramanga)','6041063','geologiayviasas@gmail.com','elb_geologia_y_vias_sas',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('900450765','ELCOSALUD','calle 52b # 31-112 (bucaramanga)','6573174','','elcosalud',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('800027004','ENCHAPES Y MADERAS','clle 7 # 15-33 lebrija (lebrija)','','enchapesymaderas@hotmail.com','enchapes_y_maderas',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('900507932','ENCONCRETO DE COLOMBIA SAS','cra 21 # 45 25 (bucaramanga)','6525559','enconcretodecolombia@gmail.com','enconcreto_de_colombia_sas',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('8002200691','EXCLUSIVOS SA','cll 93 # 49a-34 castellana (bucaramanaga)','6107100','','exclusivos_sa',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('13819350','FERRETERIA ASTIL','','','','ferreteria_astil',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('37247449','FERRETERIA EL SOL','','','','ferreteria_el_sol',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('860001607','FERRETERIA REINA','CLL 41 # 27-01','6343575','','ferreteria_reina',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('830076160','FL TRADING SA','6915352 (bucaramanga)','','fltradingsa@hotmail.com','fl_trading_sa',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('830035448','FONDO DE EMPLEADOS DE CEMEX COLOMBIA','cll 99 9a 54 p 7','6039246','mariaangelica.forero@ext.cemex.com','fondo_de_empleados_de_cemex_colombia',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('800022001','FOTO MOTO LTDA','','','','foto_moto_ltda',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('860025913','FULLER MANTENIMIENTO','cra 30 # 40a- 31 (bucaramanga)','6970388','fuller_bucaramanga@hotmail.com','fuller_mantenimiento',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('800252094','FUTURA SOLUCIONES INTEGRALES SAS','cll 45 # 28-62 (bucaramanga)','6430707','ventas@futura.com.co','futura_soluciones_integrales_sas',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('91227920','GERMAN ALBERTO SUAREZ ARIAS','caÃ±averal curaduria 2 floridablanca','','','german_alberto_suarez_arias',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('900737324','GJ CONTRATISTAS ESTRUCTURAS SAS','cra 33 # 96-01 paraguitas casa ie','316490317','','gj_contratistas_estructuras_sas',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('37834931','GOLOSINA','golosina','','','golosina',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('9004666423','GRUPO ENTRETENIMIENTO GENSAS','','','','grupo_entretenimiento_gensas',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('9004933470','GRUPO MOTOR SAS','','','','grupo_motor_sas',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('800143209','GRUPO SESPEM','valledupar (valledupar)','','contabilidad.valledupar@sespem.com','grupo_sespem',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('890206063','HARINERA DE SANTANDER LTDA','km 7 via giron (giron)','6530007','harinerasantander@hotmail.com','harinera_de_santander_ltda',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('800181509','HERRAMIENTAS Y SEGURIDAD SA','calle 21 # 14-52 (bucaramanga)','6336943','stephaniearango14@gmail.com','herramientas_y_seguridad_sa',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('900102214','HIGH PARTNER SAS','bogotá CLL 85 #49A-39','3182819129','aux.admin@highpartner.com','high_partner_SAS',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('890207407','HOGAR INFANTIL BAMBI','cll 1 # 160-86 (bucaramanga)','6630964','hibambi@hotmail.com','hogar_infantil_bambi',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('890207299','IBAÑEZ CASTILLA','km 7 via giron (giron)','6531970','','ibanez_castilla',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('900506418','IGLESIA ASD MOVIMIENTO DE REFORMA','CLL 107 # 35-139 CALDAS','6516938','','iglesia_asd_movimiento_de_reforma',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('800085445','INVERSIONES SANTOS JV LTDA','cll 44 # 28-28 (bucaramanaga)','6577125','talentohumano@santosjv.com','inversiones_santos_jv_ltda',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('900328199','JAHSALUD IPS','cll 52b # 31-112 (bucaramanga)','6573174','calidad@gruposalud.org','jahsalud_ips',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('900535833','LABORATORIO CLINICO ESPECIALIZADO CJ IPS LTDA','cra 33 # 54- 37 cabecera ','6474705','','laboratorio_clinico_especializado_cj_ips_ltda',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('13821483','LARG INGENIERIA Y CONSTRUCCION','via pamplona km 1 # 1- 97 (bucaramanga)','6340755','luisrojas@hotmail.com','larg_ingenieria_y_construccion',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('800220143','LEON Y ASOCIADOS SA','cll 41 # 27-63 edificio centro empresarial ofc 641 (bucaramanga)','6984664','bucaramanga@leonasociados.com.co','leon_y_asociados_sa',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('5560077','LUIS ALBERTO LEMUS GONZALEZ','cra 29 # 55- 68 edf alcala apt 1302 (bucaramanga)','6915352','luisalbertolego@yahoo.es','luis_alberto_lemus_gonzalez',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('860511055','MARIA LUDY CALDERON MANTILLA','calle 34 # 17 - 13 (lebrija)','6424920','','maria_ludy_calderon_mantilla',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('890101176','MEICO SA','(bucaramanga)','','','meico_sa',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('900480227','MNV COLOMBIA SAS','','','','mnv_colombia_sas',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('900406496','MULTIDISTRIBUCIONES JYJ FAMILIA','','','','multidistribuciones_jyj_familia',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('900236642','NTC INGENIERIA SAS','cra. 34 # 48 - 26 oficina 202 (bucaramanga)','689614','comercial@ntcingenieria.com','ntc_ingenieria_sas',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('811034488','ODONTOVIDA SAS','calle 54 # 31 - 122 (bucaramanga)','6470555','','odontovida_sas',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('890504378','ORGANIZACIÓN LA ESPERANZA SA','km 3.5 via - giron (giron)','6798621','','organizacion_la_esperanza_sa',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('891400378','PAPELES NACIONALES SA','','','','papeles_nacionales_sa',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('900832036','PASTOR OLARTE SAS','calle 36 # 12 - 58','6422208','','pastor_olarte_sas',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('9006541783','PLANTACIONES FLOR DE CAMPO','km 8 via piedecuesta (bucaramanga)','','viveroflorcamp@hotmail.com','plantaciones_flor_de_campo',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('900052370','PRAXIS ENGLISH ACADEMY LTDA','cll 54 # 31 - 142 antiguo campestre','6438383','','praxis_english_academy_ltda',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('800014338','PREVENIR','calle 7 # 29-55 (cali)','37003703','ordenesnacionales@prevenirsas.com','prevenir',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('800155500','PROSERVIS GENERALES SAS','','','','proservis_generales_sas',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('800020719','PROSERVIS TEMPORALES SAS','calle 47 # 29 - 33 of 604 edif herard center (bucaramanga)','6972121','cesar.delgado@proservis.com.co','proservis_temporales_sas',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('830080686','PROYECCION LABORAL','cra 23 # 86-05 polo club bogotá','2561444','','proyeccion_laboral',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('860527350','PTA SAS','carrera 34 # 52-80 (bucaramanga)','6576128','bucaramanga@pta.com.co','pta_sas',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('900152771','REHABILIDEMOS','cra 36 # 48 - 108 (bucaramanga)','6578005','','rehabilidemos',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('9008822016','RM TRANSLOGISTICA','','','','rm_translogistica',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('830029102','SALUD OCUPACIONAL DE LOS ANDES','','','','salud_ocupacional_de_los_andes',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('890312749','SEGURIDAD ATLAS','CRA 19 #28-29','6333636','','SEGURIDAD_ATLAS',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('899999034','SENA','km 2 via palogordo vereda guatiguara (pidecuesta)','6561807','','sena',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('890323239','SUMMAR TEMPORALES','cali calle 17 norte # 4n-25 -bucaramanga calle 47# 29-33 oficina 604 ','6856700','','summar_temporales',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('830063683','TECNISEG','','','','tecniseg',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('804013115','TECNOFIJACIONES SAS','cra 21 # 45-25 (bucaramanga)','6803028','tecnofijaciones@gmail.com','tecnofijaciones_sas',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('800149076','TRANSPORTE CIUDAD BONITA SA','','','','transporte_ciudad_bonita_sa',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('800066123','TYS TEMSERVICE SAS','cra 29 no. 45-94 oficina 405 (bucaramanga)','6851581','','tys_temservice_sas',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('900313631','VALMY DE COLOMBIA SAS','','','','valmy_de_colombia_sas',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('900034836','VIACOL INGENIEROS CONTRATISTAS LTDA','km1 # 1-97 via pamplona (bucaramanga)','6322852','','viacol_ingenieros_contratistas_ltda',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('900650095','VIHONCO IPS','cll 54 # 31 -30 (bucaramanga)','6973868','farmacia.bucaramanga@vihonco.com','vihonco_ips',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('804011387','VISION EMPRESARIAL','cra 34 # 51-80 piso dos (bucaramanga)','6574806','vision-e-33@hotmail.com','vision_empresarial',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('830069989','WEST ARMY SECURITY','cra 27 # 65-08 victoria (bucaramanga)','6476611','wasbucaramanga@gmail.com','west_army_security',1);

INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('800011894','FUNDACION ESTRUCTURAR','carrera 23 a # 22 b - 7 (bucaramanga)','6404926','','fundacion_estructurar',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('804012493','COOTRASEPRO','calle 45 # 19-49 piso 3 (bucaramanga)','6700997','cootasepro@hotmail.com','cootasepro',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('804016671','CAMPOLLO SA','cll 54 # 28-10 (bucaramanga)','6572206','claudia.rueda@campollo.net','campollo',1);

INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('jmso_87','COLEGIO ARCO IRIS','cl. 103 # 19 - 04/06 (bucaramanga)','6316491','arielba@yahoo.es','colegio_arco_iris',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('jmso_88','DOGGER GRILL','','','','dogger_grill',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('jmso_89','PANADERIA EL MANA CENTRO','','','','panaderia_el_mana_centro',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('jmso_90','PROYECTO TV AZTECA','','','','proyecto_tv_azteca',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('jmso_91','SOLUCIONES INMEDIATAS','','','','soluciones_inmediatas',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('jmso_92','SUMMAR PROCESOS','','','','summar_procesos',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('jmso_93','SUMMAR PRODUCTIVIDAD','','','','summar_productividad',1);
INSERT INTO company (documentId, name, address, phone, email, path, state) VALUES ('jmso_94','TECNOCONSULTEC','','','','tecnoconsultec',1);